ftp:
  host: ftp://localhost
  user: pluto
  password: password
  serverDir: files/stocks/
  downloadDir: csv
  
db:
  host: localhost
  user: root
  password: password
  database: stocks
  options_eod_table: eod_options
  optionstats_eod_table: eod_option_stats
  stockquotes_eod_table: eod_stocks
